### ISSUE TITLE
Which weights does it use ? And how to convert to .bin ?

### ISSUE THREAD

**Issue by tdurand** [sunnyden/YOLOV5_NCNN_Android#1]
Hi, 

Thanks for you work

I'm wondering which weights are you using of these provided by https://github.com/ultralytics/yolov5 ?

- YOLOv5-s
- YOLOv5-m
- YOLOv5-l
- YOLOv5-x
- YOLOv3-SPP

How did you convert to the .bin and .param file ?

Thanks

**Comment by JiaoPaner** [comment]
yolov5 has onnx convert codes，you can find it in https://github.com/ultralytics/yolov5/tree/master/models, <br>use ncnn tools convert onnx to the .bin and .param file ,that's my idea.

**Comment by tdurand** [comment]
Hi ! Thanks, before I try, could you tell me which one did you include in this repo ? I want to use the smaller one: **yolov5-s** , maybe it is already the one you used ?

**Comment by tdurand** [comment]
Just did this:

1. Converted yolov5-s weights to onnx using [onnx_export.py](https://github.com/ultralytics/yolov5/blob/master/models/onnx_export.py) 

With the following command

```
export PYTHONPATH="$PWD" && python3 models/onnx_export.py --weights ./weights/yolov5s.pt
``` 

2. Simplified with https://github.com/daquexian/onnx-simplifier

```
python3 -m onnxsim yolov5s.onnx yolov5s-simplified.onnx
```

3. Converted to ncnn using: [tools/onnx2ncnn](https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#onnx-to-ncnn)

```
./onnx2ncnn yolov5s-simplified.onnx yolov5s.param yolov5s.bin
```

BTW I get here some msgs:

```
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
```

4. Copied the yolov5s.param yolov5s.bin in assets and changed your code to use them

5. When I run the app, I get this, it doesn't seem to detect well ;-)

![Screenshot_2020-06-23-10-12-18-124_gd hq yolov5](https://user-images.githubusercontent.com/533590/85377920-17306680-b53a-11ea-9555-71377d5608e5.png)

Do you have any tips for me ?

**Comment by sunnyden** [comment]
I used the yolov5-s weights in this project. As is mentioned in the readme, I removed the slice operation by modifying the original project. For details, you could refer to issue #2.

**Comment by tdurand** [comment]
Thanks !!

**Comment by runaway** [comment]
YOLOv5s.pt是14M,你的yolov5.bin有27M，怎么差距会那么大？

**Comment by sunnyden** [comment]
The author trained the model using 16-bit float points, while ncnn only
supports 32-bit floats for models by default, therefore the size of the
model would be larger.
